### ISSUE TITLE
VS2022 build fails with commit afb5468 source producing C2084 errors "funtion  already has  a body"

### ISSUE THREAD

**Issue by jackL999** [microsoft/mimalloc#652]
`V:\\mimalloc\test\main-override.cpp(257,13): error C2084: function 'void heap_thread_free_huge_worker(void)' already has
 a body [V:\mimalloc\ide\vs2022\mimalloc-override-test.vcxproj]
V:\mimalloc\test\main-override.cpp(245,13): message : see previous definition of 'heap_thread_free_huge_worker' [V:\mim
alloc\ide\vs2022\mimalloc-override-test.vcxproj]
V:\mimalloc\test\main-override.cpp(261,13): error C2084: function 'void heap_thread_free_huge(void)' already has a body
 [V:\mimalloc\ide\vs2022\mimalloc-override-test.vcxproj]`

**Comment by daanx** [comment]
Thanks! should be fixed now
