### ISSUE TITLE
3.3.0 failing to build

### ISSUE THREAD

**Issue by mohd-akram** [microsoft/mimalloc#1270]
It fails to build on some systems:

```
/opt/local/var/macports/build/mimalloc-5f885923/work/mimalloc-3.3.0/src/alloc-override.c:99:21: error: call to undeclared library function 'aligned_alloc' with type 'void *(unsigned long, unsigned long)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    MI_INTERPOSE_MI(aligned_alloc),
                    ^
/opt/local/var/macports/build/mimalloc-5f885923/work/mimalloc-3.3.0/src/alloc-override.c:99:21: note: include the header <stdlib.h> or explicitly provide a declaration for 'aligned_alloc'
1 error generated.
```

Also, I'm not sure if it's supposed to enter that block on older systems (in this case 10.12). Full log [here](https://build.macports.org/builders/ports-10.12_x86_64-builder/builds/330031/steps/install-port/logs/stdio).

**Comment by daanx** [comment]
Ah, that is strange, the code looks like:
```c
  MI_INTERPOSE_DECLS(_mi_interposes_10_15) __OSX_AVAILABLE(10.15) = {
    MI_INTERPOSE_MI(aligned_alloc),
  };
```
so it is already checking for version 10.15 right? Maybe the attribute for available is not yet working in 10.12 ?  
If it is not too difficult, can you try replacing the above with an explicit test as:
```c
#if defined(MAC_OS_X_VERSION_10_15) && (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_15)
  MI_INTERPOSE_DECLS(_mi_interposes_10_15) = {
    MI_INTERPOSE_MI(aligned_alloc),
  };
#endif
```
Maybe we need this anyway as the `__OSX_AVAILABLE(10.15)` only sets the available attribute but perhaps the compiler still tries to resolve the `aligned_alloc`...

**Comment by mohd-akram** [comment]
Yeah, that patch worked :) Thanks

> Maybe we need this anyway as the `__OSX_AVAILABLE(10.15)` only sets the available attribute but perhaps the compiler still tries to resolve the `aligned_alloc`...

That seemed to be the case.

**Comment by mohd-akram** [comment]
The build fails on macOS 10.6 i386 for a [different reason](https://build.macports.org/builders/ports-10.6_i386-builder/builds/232632/steps/install-port/logs/stdio):

```
Undefined symbols for architecture i386:
  "_mi_prim_tls_slot", referenced from:
      _malloc in alloc.c.o
      _mi_malloc in alloc.c.o
      _mi_calloc in alloc.c.o
      _realloc in alloc.c.o
      _mi_realloc in alloc.c.o
      _strdup in alloc.c.o
      _mi_strdup in alloc.c.o
      ...
  "_mi_prim_tls_slot_set", referenced from:
      __mi_theap_cached_set in init.c.o
      __mi_theap_default_set in init.c.o
ld: symbol(s) not found for architecture i386
```

I see i386 is missing [here](https://github.com/microsoft/mimalloc/blob/ef1d67e51d98ceba1eefc5b4cd65255cbd5b7eff/include/mimalloc/prim.h#L143). Is it meant to be supported?

EDIT: It also looks like there was a check to stop the compilation from proceeding, but was removed in a7f84f36f44f543b0968e54c88d41f52eb2109f6:

```c
#if MI_TLS_SLOT
# if !defined(MI_HAS_TLS_SLOT)
#  error "trying to use a TLS slot for the default theap, but the mi_prim_tls_slot primitives are not defined"
# endif
```

**Comment by daanx** [comment]
I pushed a potential fix where we fall back to use pthreads instead. Let me know how it goes :-)

**Comment by mohd-akram** [comment]
@daanx That worked, thanks!
