### ISSUE TITLE
Fails to build on macOS < 10.12

### ISSUE THREAD

**Issue by mohd-akram** [microsoft/mimalloc#1336]
Getting this error when building on macOS 10.11 and older:

```
/opt/local/var/macports/build/mimalloc-5f885923/work/mimalloc-3.4.1/src/prim/osx/alloc-override-zone.c:228:4: error: field designator 'reinit_lock' does not refer to any field in type 'malloc_introspection_t' (aka 'struct malloc_introspection_t')
  .reinit_lock = &intro_reinit_lock,
```

**Comment by daanx** [comment]
I think this is fixed in the latest `dev3` -- let me know.

**Comment by mohd-akram** [comment]
Seems to be fixed, thanks!
