### ISSUE TITLE
dev3: compilation fails after 2048fa2d1768

### ISSUE THREAD

**Issue by solbjorn** [microsoft/mimalloc#1009]
Commit 2048fa2d1768 commented out mi_bfield_atomic_try_clear8(). With AVX2 and MI_OPT_SIMD I now get this:

```
mimalloc\src\bitmap.c(690,18): error : use of undeclared identifier 'mi_bfield_atomic_try_clear8'
  690 |     if mi_likely(mi_bfield_atomic_try_clear8(&chunk->bfields[chunk_idx], idx, NULL)) {  // clear it atomically
      |                  ^
1 error generated.
```

Is this mi_bfield_atomic_try_clear8() call still valid or should be replaced with something else?

**Comment by solbjorn** [comment]
Fixed, thanks!
